package br.com.visent.analise.enums;

public enum ComponenteFiltro {

	CAMPO_CHECKBOX,
	CAMPO_COMBOBOX,
	CAMPO_LISTDOUBLE_ID,
	CAMPO_LISTDOUBLE_STRING,
	CAMPO_NUMERICO,
	CAMPO_TEXTFIELD,
	CAMPO_TEXTLIST,
	TREE
	
}
